<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?php echo $this->layout['meta_title'];?></title>
        <link rel="shortcut icon" type="/image/png" href="/img/ico.png"/>
        <link rel="icon" type="/image/png" href="/img/ico.png"/>
        <link rel="apple-touch-icon" href="/img/ico.png" />
        <script type="text/javascript" SRC="/js/jquery-1.4.2.min.js"></script>       
    </head>
    <body>
        <?php
        echo $this->content;
        ?>
    </body>
</html>