<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?php echo $this->layout['meta_title'];?></title>
        <link rel="shortcut icon" type="/image/png" href="/img/ico.png"/>
        <link rel="icon" type="/image/png" href="/img/ico.png"/>
        <link rel="apple-touch-icon" href="/img/ico.png" />
        <link rel="stylesheet" href="/css/styles.css" type="text/css" />
        <link rel="stylesheet" href="/css/custom.css" type="text/css" />
        <script type="text/javascript" SRC="/js/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" SRC="/js/jquery.ui.widget.min.js"></script>
        <script type="text/javascript" SRC="/js/jquery.ui.tabs.min.js"></script>
        <!-- jQuery tooltips -->
        <script type="text/javascript" SRC="/js/jquery.tipTip.min.js"></script>
        <!-- Superfish navigation -->
        <script type="text/javascript" SRC="/js/jquery.superfish.min.js"></script>
        <script type="text/javascript" SRC="/js/jquery.supersubs.min.js"></script>
        <!-- jQuery form validation -->
        <script type="text/javascript" SRC="/js/jquery.validate_pack.js"></script>
        <!-- jQuery popup box -->
        <script type="text/javascript" SRC="/js/jquery.nyroModal.pack.js"></script>        
    </head>
    <body>
        <?php
        echo $this->content;
        ?>
    </body>
</html>